AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: JAR.io Backend

Resources:
  JARioFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers.lambda_handler.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          TABLE_NAME: JARio
          LOG_LEVEL: DEBUG
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ScrapbookApi:
          Type: Api
          Properties:
            Path: /scrapbook/{operation}
            Method: ANY

Outputs:
  JARioApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrapbook/{operation}"